adventureworksLH:
  outputs:
    test:
      catalog: test_edp
      host: "{{ env_var('DBT_ENV_SECRET_DBRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_ENV_SECRET_DBRICKS_HTTP_PATH') }}"
      schema: lakehouse
      threads: 4
      token: "{{ env_var('DBT_ENV_SECRET_DBRICKS_ACCESS_TOKEN') }}"
      type: databricks
  target: test
elementary:
  outputs:
    default:
      type: "databricks"
      host: "{{ env_var('DBT_ENV_SECRET_DBRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_ENV_SECRET_DBRICKS_HTTP_PATH') }}"
      catalog: "test_edp"
      schema: "lakehouse_logs"
      token: "{{ env_var('DBT_ENV_SECRET_DBRICKS_ACCESS_TOKEN') }}"
      threads: 4